[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags = -Wl,-z,muldefs
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
extra_scripts = pre:scripts/sprite_generator.py
lib_deps =
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    ESP32Ping